---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backend-db
  namespace: default
spec:
  encryptedData:
    password: AgAbOyxYOGDVMQuwAkSLCh1Hti6/kpBv1nHoQyNmcT/QYOZCmu5SxSNjzlUdkQdVZKjXtQWSz6iSiSPUUS62ZOy44N2jFN+QllKtUXy/01MTweSG1L+5z4IkwOKGBMYpbwsPfeR2HoPRX7QdHqFRkI2EBMnA3aBP5mzkTQ2ET1H31oZhZ7Gk+LVk+qSFdzJTmV95h7yVpMOZySQEnD2lHXmThbFlQIStVoU+L+fR+MnvSwhQpHG4VEA0B4+gtj2Xh55NKnCGT0YLBbM7YPeXqxHiW9G/bkjsg1zz6z+mCfc3IONEHjwZu/6t1ZvSO3EUZGp9o/uu+sDU/hIn2+HKdEnVKwCn3BF3xmSnCF2B2Jl7xQg4f2MLQ7Ia/JJpoVu38HPYhHd0HMkCXCPZgpQGwN7iioqUwcKYBxDP+JBJmvnIHNElv3LkQHAsdzGQzhv8crtmW5ZpHQlrecWbdxmqAg4aXF0Jx7WQ4KV+L4icb9wj0Rf2zSAOa/ZOMYngAdHAVGlGFVJrWMvoZZb6S7ifnaf2zfxj3ksVCpe2XFe7yqRgv+cLKESj0+BIfrvO4A7RgjoyFQgfuJsTJ+fqAA/x4X33vGSqAeaSiMdXg12jhdV6qYJYkTlGwacLhq0gx/a2KCyw73Zk6XWnHISZjlSD+SxQV6A2JE26wHnaNuBgb88vD4gElbIO2tvhZ1YeG8hHrXiL7XH0pSH0abUaOvxsrw==
    username: AgA79fFJlA9DdCnVOat3BcN+/0HI3Y2e4IQkAOijmzY/xc74sU4p0JSD45Xhu1uQCBwVP81L3tircm/Qu2jVLxzP2R7lM/oNOVcaoWdUJkCuJsFDjA2FkKvNfrwwEaDT5KKW72x1oyWUH9VIcMjzZM+mN/SMqDwGylS4q/ykg+73yp+BfzFCjqKek+AKd68E11Pxfry7Fe5wFrmJSlsifMip6w3hNolooFhDMdpr8VVoy0acjUfk6B3nw8d/2UfxOX2ZdLA6279Lx+Fdd8sAEADjZwamUj99WX6t36xDztY1EqBYpJP7RKCwSLl96Gsj358OrMaNIt+qK2AnBfZKFlvlZNF1CQG+EMJ4lahPehyDh70CWChT9fF89cLts3X90a8V0cZOUzuboSC9GQD7p4cg8eg7a1qBgP+HpESxfj2Ax7WTMfmBHjdG8Ozf23fWwy0tytkmGm5yaUYh4PpUqWFXnFnZn+cXK6BUTEY5f1KRw0xzZQrkIiddZurWA9Vg44rmtPJzp7mbjBehYZ9f4SvFkWUmFBpsTtJFeGS5Enqi4cI5QfYErsQrHnBphorGwY60nohVH7HKq7RagVJSvMdPPsvDEzZfw0zukJJ/7c9v3tK6V6zMcMC51OnAVfQMVJfJW1GZFcC6kcig/oe8ga1XgJur2NVglo4o16bq10PmSU2HaYPYrtJQVT1Dpl07dIul/ws+6g==
  template:
    metadata:
      name: backend-db
      namespace: default
