apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-deploy
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Alekslisk/helm-charts.git
    targetRevision: main
    path: charts/myapp # <--- ВОТ ЧТО НУЖНО БЫЛО ИЗМЕНИТЬ
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true