apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-ingress
  namespace: argocd
spec:
  project: default
  sources:
    # Источник 1: Официальный Helm-чарт Traefik
    - repoURL: https://traefik.github.io/charts
      chart: traefik
      targetRevision: 34.0.0
      # Блок helm должен быть здесь, привязанный к самому чарту!
      helm:
        valueFiles:
          - $my-values-repo/infra/traefik/values.yaml
    
    # Источник 2: ВАШ Git-репозиторий
    - repoURL: https://github.com/Alekslisk/helm-charts.git
      targetRevision: HEAD
      ref: my-values-repo

  destination:
    server: https://kubernetes.default.svc
    namespace: traefik

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true